### ISSUE TITLE
/usr/bin/mpd: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ndarilek** [Tob1asDocker/rpi-mpd#1]
Getting this error when trying to launch your image on a fresh, up-to-date RPi 3 b+. I'll see if I can submit a PR to fix this, but in case I can't get around to it, I thought I'd file this.

Thanks!

**Comment by lucas-pouchot-zz** [comment]
Hi, I got the same error on a RPi 3 b (not b+).

**Comment by gallzoltan** [comment]
I got also this error on:
Linux pidocker 4.14.34-hypriotos+ #2 Sun Apr 22 15:29:32 UTC 2018 armv6l GNU/Linux
ARMv6-compatible processor rev 7 (v6l)

**Comment by Tob1as** [comment]
Sorry for my late answer. I can't find the error currently. It works for me (Raspberry Pi 3B)

(Note to me, should the error appear again, then take a look here:  https://github.com/dendevs/docker-rpi-mpd )
