### ISSUE TITLE
Update to Alpine 3.10 base image

### ISSUE THREAD

**Issue by moretocome** [Tob1asDocker/rpi-mpd#2]
Thank you for this contribution. I have been searching long for an actual working ARM version om MPD in Docker, and I finally found it here.

I noticed though, that the Alpine version is still using a 3.9 base image, even though Alpine 3.10 was released a couple of months ago. That unfortunately means the installed MPD will be limited to version 0.20.21-r4, which is a shame when 0.21.10-r0 is already available on 3.10.

I filed an [issue](https://github.com/balena-io-library/base-images/issues/557) with @balena-io-library, but there does not seem to be much activity in the repositoty, so it might be time to switch to a new base image, since other updated options are already available on Dockerhub.

Thanks in advance in any case! :)

**Comment by Tob1as** [comment]
I have a new Image with Alpine 3.10 and MPD 0.21.10. I tested it on a RPi 2. :)

details:  
Change from [balenalib/raspberry-pi-alpine:3.9 (armv6)](https://www.balena.io/docs/reference/base-images/base-images-ref/) to [arm32v6/alpine:3.10](https://hub.docker.com/r/arm32v6/alpine/)  (but I'm thinking about switching to [arm32v7/alpine:3.10](https://hub.docker.com/r/arm32v7/alpine/) ...) 

Please test it ;)

**Comment by moretocome** [comment]
I updated with Watchtower and everything seems to be running smooth.

At least according to this [comment](https://github.com/gliderlabs/docker-alpine/issues/298#issuecomment-309561787) there should be a performance increase in moving to arm32v7, so that would probably be great :)

I also run it on a Raspberry Pi 2.

Thanks a lot for your effort!

**Comment by moretocome** [comment]
Minor differences:

1. The user the container is run under switched from ```systemd-network``` to ```systemd-timesync``` so I had to ```chown``` my data folder.
2. Is see this message in the log now, which I haven't noticed before:
```
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
```
I'm not sure whether it causes any problems. I use this instance in a satellite setup so it does not have any sound output but only serves the database for other daemons on different devices on the network, at that ability does not seem to be affected.

**Comment by moretocome** [comment]
I have been running you image for several days now without a glitch except for the mentioned warning, so I will close the issue, @Tob1as  :)
