### ISSUE TITLE
setpoint volume

### ISSUE THREAD

**Issue by d-ani** [Tob1asDocker/rpi-mpd#3]
Hello,
i can't change the setpoint for the volume.
The value is always 0. When i try to change the value i receive an error.

**Comment by Tob1as** [comment]
Hello,
what's the exact error message?

In my configuration http is enabled as the only output. The volume has no effect there.
If you want to use the jack sound output of the Pi, you have to adjust the configuration (audio_output) accordingly and mount corresponding devices when starting the container.
