### ISSUE TITLE
docker tobi312/rpi-mpd does not work 

### ISSUE THREAD

**Issue by shredman01** [Tob1asDocker/rpi-mpd#4]
Hi tobi,

your docker container  tobi312/rpi-mpd does not work. when I start it with docker-compose up -d, the containers restarts again and again. can you help? use it on a raspberry pi 3B+ with latest docker & docker-compose installed. 

pi@raspberrypi:/opt/mpd/etc $ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                  PORTS                                            NAMES
e9c59bb5a3dd   tobi312/rpi-mpd:latest   "/usr/bin/mpd --no-d…"   14 seconds ago   Up Less than a second   0.0.0.0:6600->6600/tcp, 0.0.0.0:8000->8000/tcp   mpd
pi@raspberrypi:/opt/mpd/etc $ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                         PORTS     NAMES
e9c59bb5a3dd   tobi312/rpi-mpd:latest   "/usr/bin/mpd --no-d…"   17 seconds ago   Restarting (1) 2 seconds ago             mpd
pi@raspberrypi:/opt/mpd/etc $ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS        PORTS                                            NAMES
e9c59bb5a3dd   tobi312/rpi-mpd:latest   "/usr/bin/mpd --no-d…"   20 seconds ago   Up 1 second   0.0.0.0:6600->6600/tcp, 0.0.0.0:8000->8000/tcp   mpd
pi@raspberrypi:/opt/mpd/etc $ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                        PORTS     NAMES
e9c59bb5a3dd   tobi312/rpi-mpd:latest   "/usr/bin/mpd --no-d…"   22 seconds ago   Restarting (1) 1 second ago             mpd

# docker-compuse.yml
version: '2.4'
services:
  mpd:
    image: tobi312/rpi-mpd:latest
    container_name: mpd
    ports:
      - 6600:6600
      - 8000:8000
    volumes:
      - ./music:/var/lib/mpd/music:rw
      - ./playlists:/var/lib/mpd/playlists:rw
      - ./etc/mpd.conf:/etc/mpd.conf
      #- ./data:/var/lib/mpd/data:rw
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/snd:/dev/snd"
    restart: always

**Comment by Tob1as** [comment]
Hi,

to be able to help, I needed the log of the container: ```docker logs mpd```

**Comment by shredman01** [comment]
Hallo Tobias,

 

ich antworte jetzt mal auf Deutsch. Ich würde gerne einen Log liefern aber im mpd Verzeichnis wird nichts gespeichert. Zur Instalation: 

Ich habe in /opt das mpd Verzeichnis erstellt, darin die docker-compose.yml von der Anleitung erstellt und den container mit docker pull tobi312/rpi-mpd geholt

 

Mit dem docker-compose up –d  wird zwar der Container gestartet aber er stoppt und startet immer und immer wieder. Er geht nicht auf up. Im /opt/mpd Verzeichnis ist außer den Verzeichnissen auch kein Inhalt zu sehen.

 

Gruß,

Frank 

 

Von: Tobias Hargesheimer [mailto:notifications@github.com] 
Gesendet: Samstag, 30. Januar 2021 18:47
An: Tob1asDocker/rpi-mpd
Cc: shredman01; Author
Betreff: Re: [Tob1asDocker/rpi-mpd] docker tobi312/rpi-mpd does not work (#4)

 

Hi,

to be able to help, I needed the log of the container: docker logs mpd

**Comment by Tob1as** [comment]
Die Logs werden nicht als Datei abgelegt, diese werden in der Konsole ausgegeben. Du kannst diese mit den Befehlen `docker logs mpd` oder auch `docker-compose logs mpd` anschauen. Mit einem `> mpd.log` hinter einem Befehl kannst du diese als Datei speichern. (Wenn du den Logs in der Konsole "folgen" möchtest, kannst du hinter "logs" und vor "mpd" noch den Parameter `-f` verwenden. Mit Strg+C beendest du das "folgen" wieder.)

* Die Ordner Music und Playlist musst du füllen. ;)
* Liegt im Ordner /etc auch die mpd.conf? 
  * Hast du deine Konfiguration (mpd.conf) mal überprüft oder hast du meine mpd.conf unverändert gelassen?
* Falls du Daten (mpd Datenbank usw.) behalten willst, kommentier im docker-compose folgendes ein: `- ./data:/var/lib/mpd/data:rw`  (also das # entfernen)
* Versuche mal die Ordnerrechte zu ändern: `sudo chmod 777 /opt/mpd/{music,playlists,data}` und starte dann mpd neu.

**Comment by shredman01** [comment]
Hallo Tobias,

 

erst einmal danke für Deine Hilfe. Ich habe den Container noch mal gestartet

 


socket: Address already in use
mpd    | hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
mpd    | exception: Failed to open '/var/lib/mpd/data/database': No such file or directory
mpd    | exception: Failed to open database plugin
mpd    | exception: nested: On parent directory of db file
mpd    | exception: Failed to access /var/lib/mpd/data: No such file or directory
mpd    | exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
mpd    | hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
mpd    | exception: Failed to open '/var/lib/mpd/data/database': No such file or directory
mpd    | exception: Failed to open database plugin
mpd    | exception: nested: On parent directory of db file
mpd    | exception: Failed to access /var/lib/mpd/data: No such file or directory
mpd    | exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
mpd    | hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
mpd    | exception: Failed to open '/var/lib/mpd/data/database': No such file or directory
mpd    | exception: Failed to open database plugin
mpd    | exception: nested: On parent directory of db file
mpd    | exception: Failed to access /var/lib/mpd/data: No such file or directory

 

 
version: '2.4'


services:
  mpd:
    image: tobi312/rpi-mpd:latest
    container_name: mpd
    network_mode: host
    ports:
      - 6600:6600
      - 8000:8000
    volumes:
      - ./music:/opt/mpd/music:rw
      - ./playlists:/opt/mpd/playlists:rw
      - ./data:/opt/mpd/data:rw
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/snd:/dev/snd"
    restart: unless-stopped

 

 


pi@raspberrypi:/opt/mpd $ ls -als
insgesamt 28
4 drwxr-xr-x 6 docks docks 4096 Feb  3 16:20 .
4 drwxr-xr-x 8 root  root  4096 Jan 30 13:47 ..
4 drwxr-xr-x 2 root  root  4096 Jan 30 14:01 data
4 -rw-r--r-- 1 root  root   432 Feb  3 16:20 docker-compose.yml
4 drwxr-xr-x 2 root  root  4096 Feb  3 16:16 etc
4 drwxr-xr-x 2 root  root  4096 Jan 30 14:01 music
4 drwxr-xr-x 2 root  root  4096 Jan 30 14:01 playlists
pi@raspberrypi:/opt/mpd $

 

 

Egal was ich auch in der docker-compose.yml an Pfaden ändere, im Log kommt immer das Gleiche

 

 

Funktioniert irgendwie nicht der Container. Frage mich wo der Fehler liegt.



 



Gruß,

Frank Hofmann


Gesendet: Dienstag, 02. Februar 2021 um 19:24 Uhr
Von: "Tobias Hargesheimer" <notifications@github.com>
An: "Tob1asDocker/rpi-mpd" <rpi-mpd@noreply.github.com>
Cc: "shredman01" <shred_online@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Tob1asDocker/rpi-mpd] docker tobi312/rpi-mpd does not work (#4)


 

Die Logs werden nicht als Datei abgelegt, diese werden in der Konsole ausgegeben. Du kannst diese mit den Befehlen docker logs mpd oder auch docker-compose logs mpd anschauen. Mit einem > mpd.log hinter einem Befehl kannst du diese als Datei speichern. (Wenn du den Logs in der Konsole "folgen" möchtest, kannst du hinter "logs" und vor "mpd" noch den Parameter -f verwenden. Mit Strg+C beendest du das "folgen" wieder.)


	Die Ordner Music und Playlist musst du füllen. ;)
	Liegt im Ordner /etc auch die mpd.conf?
	
		Hast du deine Konfiguration (mpd.conf) mal überprüft oder hast du meine mpd.conf unverändert gelassen?
	
	
	Falls du Daten (mpd Datenbank usw.) behalten willst, kommentier im docker-compose folgendes ein: - ./data:/var/lib/mpd/data:rw (also das # entfernen)
	Versuche mal die Ordnerrechte zu ändern: sudo chmod 777 /opt/mpd/{music,playlists,data}

**Comment by shredman01** [comment]
Hi, ich noch mal

 

was noch nicht ganz verstehe. Der mpd für sich installiert ohne Docker benutzt ja den Pfad /var/lib/mpd/data aber wenn ich docker benutzen möchte ist doch der Pfad nicht relevant oder muss mpd als Paket installiert werden ?

 

./data: /var/lib/mpd/data:rw

 

im /opt/mpd Verzeichnis wo die docker-compse.yml liegt wird zwar beim start mit docker-compose up  -d der Ordner data erstellt aber der bleibt immer leer. Im log steht ja

 


socket: Address already in use
mpd    | hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
mpd    | exception: Failed to open '/var/lib/mpd/data/database': No such file or directory
mpd    | exception: Failed to open database plugin
mpd    | exception: nested: Can't create db file in "/var/lib/mpd/data": Permission denied

 

Wieso versucht der auf das Filesystem des Raspberry zuzugreifen, dachte die Datenbank wird im /opt/mpd erzeugt.

 

Gruß,

Frank Hofmann


 

 

Gesendet: Dienstag, 02. Februar 2021 um 19:24 Uhr
Von: "Tobias Hargesheimer" <notifications@github.com>
An: "Tob1asDocker/rpi-mpd" <rpi-mpd@noreply.github.com>
Cc: "shredman01" <shred_online@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Tob1asDocker/rpi-mpd] docker tobi312/rpi-mpd does not work (#4)


 

Die Logs werden nicht als Datei abgelegt, diese werden in der Konsole ausgegeben. Du kannst diese mit den Befehlen docker logs mpd oder auch docker-compose logs mpd anschauen. Mit einem > mpd.log hinter einem Befehl kannst du diese als Datei speichern. (Wenn du den Logs in der Konsole "folgen" möchtest, kannst du hinter "logs" und vor "mpd" noch den Parameter -f verwenden. Mit Strg+C beendest du das "folgen" wieder.)


	Die Ordner Music und Playlist musst du füllen. ;)
	Liegt im Ordner /etc auch die mpd.conf?
	
		Hast du deine Konfiguration (mpd.conf) mal überprüft oder hast du meine mpd.conf unverändert gelassen?
	
	
	Falls du Daten (mpd Datenbank usw.) behalten willst, kommentier im docker-compose folgendes ein: - ./data:/var/lib/mpd/data:rw (also das # entfernen)
	Versuche mal die Ordnerrechte zu ändern: sudo chmod 777 /opt/mpd/{music,playlists,data}

**Comment by Tob1as** [comment]
Die Zeile sagt es schon:
`mpd    | exception: Failed to access /var/lib/mpd/data: No such file or directory`
oder auch
`mpd    | exception: nested: Can't create db file in "/var/lib/mpd/data": Permission denied`

Schau mal ob bei dir am Dateisystem in deinem Ordner ein "data" Ordner erstellt ist, wenn ja ändere die Rechte, so wie bereits beschrieben.
Außerdem solltest du im Container die Pfade wieder auf die "Standardwerte" setzen statt `/opt/mpd/...`, da du in dem docker-compose file keine eigene Konfig verwendest, wird das so nicht funktionieren.

Schritt für Schritt:
1. `mkdir mympd` (also ein Ordner für mpd irgendwo erstellen, z.B. /home/pi)
2. `cd mympd`
3. `wget https://github.com/Tob1asDocker/rpi-mpd/raw/master/docker-compose.yml -O docker-compose.yml` oder die aus der ReadMe kopieren, außer mehr auskommentierte Zeilen kein Unterschied.
4. `wget https://github.com/Tob1asDocker/rpi-mpd/raw/master/mpd.conf -O mpd.conf`
5. `mkdir {music,playlists,data}`
6. `chmod 777 {music,playlists,data,mpd.conf}`
7. Optional, wenn du die lokale mpd.conf aus Schritt 4 nutzen möchtest, dann kommentiere das in docker-compose.yml ein.
8. `docker-compose up -d`

So sollte es auf jedenfall funktionieren.


**EDIT: Sehe gerade erst, dass du nochmal geantwortest hast, während ich den Beitrag schreibe.**
Die Daten die im Container im Odner `/var/lib/mpd` und Unterordner liegen werden lokal auf deinem Dateisystem geschrieben, in der dein docker-compose liegt (das kommt duch die Angabe von `./`), dein vollständiger Pfad im lokalen System ist bei dir also `/opt/mpd/ORDNERNAME`. Das ganze geht auch ohne Zugriff auf das lokale Dateisystem, dann sind aber nach einem "neustart" des Containers die Daten weg. Allerdings braucht der Ordner andere Rechte, damit der Container darin auch schreiben darf, deswegen `777` (ist am einfachsten).

**Comment by shredman01** [comment]
Hallo Tobias,

 

das hat soweit schon mal funktioniert. Jetzt läuft der docker container und der MPDroid auf dem Android Phone connected auch zu Port 6600 auf dem raspberrypi aber ich hör nichts auf dem Handy. 

Mein Plan ist eigentlich auch das der Raspberry per 3.5 mm Klinke > Chinch an den Hifi Verstärker angebunden wird und ich per MPDroid die MP3 Files anklicken und spielen kann. Müsste doch gehen, oder ? 

 

Habe in den music Ordner eine Albun gelegt das auch vom Client erkannt wird und auch abgespielt wird, jedoch ohne Ton. 

 

Für den Raspberry Ton habe ich folgendes auskommentiert aber weiß noch nicht ob es richtig ist

 

# An example of an ALSA output:

#

audio_output {

        type            "alsa"

        name            "My ALSA Device"

        device          "hw:0,0"        # optional

        mixer_type      "software"      # optional

#       mixer_device    "default"       # optional

#       mixer_control   "PCM"           # optional

#       mixer_index     "0"             # optional

}

 

Gruß,

Frank

 

 

mpd    | exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use

mpd    | hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled

mpd    | exception: Input plugin 'tidal' is unavailable: No Tidal application token configured

mpd    | exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured

mpd    | exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted

mpd    | avahi: Failed to create client: Daemon not running

mpd    | exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted

mpd    | exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted

mpd    | exception: bind to '0.0.0.0:8000' failed (continuing anyway, because binding to '[::]:8000' succeeded): Failed to bind socket: Address already in use

mpd    | client: [0] opened from 192.168.1.113:49010

mpd    | client: [1] opened from 192.168.1.113:49012

mpd    | client: [0] closed

mpd    | client: [2] opened from 192.168.1.113:49022

mpd    | client: [3] opened from 192.168.1.113:49024

mpd    | client: [2] closed

mpd    | client: [4] opened from 192.168.1.113:49028

mpd    | client: [5] opened from 192.168.1.113:49034

mpd    | exception: bind to '0.0.0.0:8000' failed (continuing anyway, because binding to '[::]:8000' succeeded): Failed to bind socket: Address already in use

 

Von: Tobias Hargesheimer [mailto:notifications@github.com] 
Gesendet: Mittwoch, 3. Februar 2021 18:21
An: Tob1asDocker/rpi-mpd <rpi-mpd@noreply.github.com>
Cc: shredman01 <shred_online@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Tob1asDocker/rpi-mpd] docker tobi312/rpi-mpd does not work (#4)

 

Die Zeile sagt es schon:
mpd | exception: Failed to access /var/lib/mpd/data: No such file or directory
oder auch
mpd | exception: nested: Can't create db file in "/var/lib/mpd/data": Permission denied

Schau mal ob bei dir am Dateisystem in deinem Ordner ein "data" Ordner erstellt ist, wenn ja ändere die Rechte, so wie bereits beschrieben.
Außerdem solltest du im Container die Pfade wieder auf die "Standardwerte" setzen statt /opt/mpd/..., da du in dem docker-compose file keine eigene Konfig verwendest, wird das so nicht funktionieren.

Schritt für Schritt:

1.	mkdir mympd (also ein Ordner für mpd irgendwo erstellen, z.B. /home/pi)
2.	cd mympd
3.	wget https://github.com/Tob1asDocker/rpi-mpd/raw/master/docker-compose.yml -O docker-compose.yml oder die aus der ReadMe kopieren, außer mehr auskommentierte Zeilen kein Unterschied.
4.	wget https://github.com/Tob1asDocker/rpi-mpd/raw/master/mpd.conf -O mpd.conf
5.	mkdir {music,playlists,data}
6.	chmod 777 {music,playlists,data,mpd.conf}
7.	Optional, wenn du die lokale mpd.conf aus Schritt 4 nutzen möchtest, dann kommentiere das in docker-compose.yml ein.
8.	docker-compose up -d
So sollte es auf jedenfall funktionieren.

EDIT: Sehe gerade erst, dass du nochmal geantwortest hast, während ich den Beitrag schreibe.
Die Daten die im Container im Odner /var/lib/mpd und Unterordner liegen werden lokal auf deinem Dateisystem geschrieben, in der dein docker-compose liegt (das kommt duch die Angabe von ./), dein vollständiger Pfad im lokalen System ist bei dir also /opt/mpd/ORDNERNAME. Das ganze geht auch ohne Zugriff auf das lokale Dateisystem, dann sind aber nach einem "neustart" des Containers die Daten weg. Allerdings braucht der Ordner andere Rechte, damit der Container darin auch schreiben darf, deswegen 777 (ist am einfachsten).

**Comment by Tob1as** [comment]
MPDroid / Port 6600 ist nur zum Steuern. Um die Musik als Stream am Client zu hören rufe über den Web-Browser oder z.B: VLC Player den Port 8000 auf (http://IP-der-PI:8000 ).

Den Ton über Klinke ausgeben, kann funktionieren, ich hab es selbst so aber nicht in Verwendung und auch (aktuell) keine Möglichkeit entsprechende Konfigurationen zu testen. Ich nutze es nur als Stream.

**Comment by shredman01** [comment]
so, funktioniert jetzt alles soweit. Selbst am Handy kann ich jetzt den Stream hören. Ist mit etwas versatz wenn man mit MPDroid über 6600 die Lieder steuert aber das ist ok so. Werde mal mit dem Raspberry die Ausgabe auf die Audio Klinkenbuchse testen, sollte eigentlich auch funktionieren. Mit nem Kodi hat es jedenfalls damals schon mal funktioniert. Dann noch mal vielen Dank für Deine Hilfe ;-)

 

Gruß,

Frank

 

Gesendet: Mittwoch, 03. Februar 2021 um 21:01 Uhr
Von: "Tobias Hargesheimer" <notifications@github.com>
An: "Tob1asDocker/rpi-mpd" <rpi-mpd@noreply.github.com>
Cc: "shredman01" <shred_online@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Tob1asDocker/rpi-mpd] docker tobi312/rpi-mpd does not work (#4)


 

MPDroid / Port 6600 ist nur zum Steuern. Um die Musik als Stream am Client zu hören rufe über den Web-Browser oder z.B: VLC Player den Port 8000 auf (http://IP-der-PI:8000 ).

Den Ton über Klinke ausgeben, kann funktionieren, ich hab es selbst so aber nicht in Verwendung und auch (aktuell) keine Möglichkeit entsprechende Konfigurationen zu testen. Ich nutze es nur als Stream.

**Comment by shredman01** [comment]
Hallo Tobias,

 

sorry das ich Dich noch mal nerve aber ich hätte einen Verbessungsvorschlag für Deinen tobi312/rpi-mpd Docker Container. Wäre es möglich das Du den Container dahingehend erweiterst das man den Also Equalizer benutzen kann ? Ich habe mittlerweile alles versucht aber es ist leider nicht möglich nach den diversen Anleitungen im Netz dem Docker mpd eine geänderte  Soundquelle aus einer .asoundrc oder /etc/ascound.conf mit zu geben. Ich vermute im Container fehlen die dazu nötigen Plugins und Voraussetzungen für den Einsatz des Alsa Equalizers ?

 

https://kb.gtkc.net/mpd-with-the-alsa-equalizer-plugin/

 

### .asoundrc

 

pcm.!default {

  type plug

  slave.pcm plugequal;

}

ctl.!default {

  type hw card 0

}

ctl.equal {

  type equal;

}

pcm.plugequal {

  type equal;

  slave.pcm "plughw:2,0"; # NOTE this line MUST be your hardware device.

}

pcm.equal {

  type plug;

  slave.pcm plugequal;

}

 

#### mpd.conf

 

audio_output {

        type "alsa"

        name "Ugreen USB extern"

        device "hw:2"

#       device        "plug:plugequal"

        mixer_type "software"

        format          "44100:16:2"

#       mixer_device "default"

#       mixer_control "MPD"

}

 

Diese mpd.conf Konfiguration funktioniert einwandfrei aber sobald ich die Zeile device   "plug:plugequal“ ein und die #device "hw:2" rausnehme klappt es nicht mehr.

 

root@raspberrypi:/opt/mpd# docker-compose up

Creating network "mpd_default" with the default driver

Creating mpd ... done

Attaching to mpd

mpd    | hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled

mpd    | exception: Input plugin 'tidal' is unavailable: No Tidal application token configured

mpd    | exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured

mpd    | exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted

mpd    | avahi: Failed to create client: Daemon not running

mpd    | exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted

mpd    | exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted

mpd    | exception: bind to '0.0.0.0:8000' failed (continuing anyway, because binding to '[::]:8000' succeeded): Failed to bind socket: Address already in use

mpd    | ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM plugequal

mpd    | exception: Failed to open "Ugreen USB extern" (alsa)

mpd    | exception: nested: Failed to open ALSA device "plug:plugequal": No such file or directory

 

 

Wäre es möglich den Container für das Equalizer zu ändern ? Das wäre mega cool wenn man den Sound vom mpd noch verändern könnte, die Ugreen USB Soundkarte klingt zwar schon wesentlich besser aber so bischen mehr Höhen und Bässe nachregeln wäre schon gut. 

 

Danke im voraus.

 

Gruß,

Frank Hofmann

 

Von: Tobias Hargesheimer [mailto:notifications@github.com] 
Gesendet: Donnerstag, 4. Februar 2021 22:38
An: Tob1asDocker/rpi-mpd <rpi-mpd@noreply.github.com>
Cc: shredman01 <shred_online@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Tob1asDocker/rpi-mpd] docker tobi312/rpi-mpd does not work (#4)

 

Closed #4 <https://github.com/Tob1asDocker/rpi-mpd/issues/4> .

**Comment by Tob1as** [comment]
Da ich dieses Setup so nicht testen kann, werde ich das nicht einbauen. Du kannst gerne mein Image als Basis-Image verwenden und mit einem eigenen Dockerfile erweitern.
