### ISSUE TITLE
Debian Image clips ends of mp3s when using alsa output

### ISSUE THREAD

**Issue by laheym** [Tob1asDocker/rpi-mpd#6]
I noticed that when I am using ALSA output on rasberry pi 3, with the Debian image, every single mp3 is clipped a few seconds before it is completed. When I switch to the Alpine image the problem goes away. 

I am using this for local notifications from Home Assistant(HA).  http streaming output is disabled

Here is the output section of my MPD.conf: 

```
audio_output {
        type            "alsa"
        name            "My ALSA Device"
#       device          "hw:0,0"        # optional
#       mixer_type      "hardware"      # optional
#       mixer_device    "default"       # optional
        mixer_control   "Headphone"             # optional
#       mixer_index     "0"             # optional
}
```

**Comment by Tob1as** [comment]
May be due to the different versions of MPD in the linux distributions....
