### ISSUE TITLE
Logs show exception

### ISSUE THREAD

**Issue by Curious-r** [Tob1asDocker/rpi-mpd#7]
`exception: Failed to create Avahi client: Daemon not running`

My environment is raspberrypi 4B with raspberrypiOS-64. The compose.yaml is as follow:
`version: '3.8'
services:
  mpd:
    #image: tobi312/rpi-mpd:debian
    image: tobi312/rpi-mpd:alpine
    container_name: mpd
    restart: unless-stopped
    ports:
      - 6600:6600  # MPD Client
      - 8000:8000  # Stream
    volumes:
      - ./music:/var/lib/mpd/music:rw
      - ./playlists:/var/lib/mpd/playlists:rw
      - ./data:/var/lib/mpd/data:rw
      - ./mpd.conf:/etc/mpd.conf:rw
    devices:
      - /dev/snd:/dev/snd`

**Comment by Tob1as** [comment]
I have now disable zeroconf in [mpd.conf](https://github.com/Tob1as/docker-mpd/blob/master/mpd.conf#L153), by default it is enabled https://mpd.readthedocs.io/en/latest/user.html#zeroconf

**Comment by Curious-r** [comment]
> I have now disable zeroconf in [mpd.conf](https://github.com/Tob1as/docker-mpd/blob/master/mpd.conf#L153), by default it is enabled https://mpd.readthedocs.io/en/latest/user.html#zeroconf

It works, thanks a lot!
